name       : krename
version    : 5.0.0
release    : 1
source     :
    - https://cdn.download.kde.org/stable/krename/5.0.0/src/krename-5.0.0.tar.xz : 0a61761853787fd46b35f3a733cf87cde00de5df631728332a64c38c670bd28c
license    : GPL-2.0
component  : desktop.kde
summary    : Utility to handle specialised file renames
description: |
    KRename is a very powerfull batch file renamer by KDE. It allows you to easily rename hundreds or even more files in one go. The filenames can be created by parts of the original filename, numbering the files or accessing hundreds of informations about the file, like creation date or Exif information of an image.
builddeps  :
    - pkgconfig(exiv2)
    - pkgconfig(freetype2)
    - pkgconfig(gl)
    - pkgconfig(libpodofo-0)
    - pkgconfig(Qt5Core)
    - pkgconfig(taglib)
    - extra-cmake-modules
    - kcompletion-devel
    - kconfig-devel
    - kcoreaddons-devel
    - kcrash-devel
    - ki18n-devel
    - kiconthemes-devel
    - kio-devel
    - kitemviews-devel
    - kjobwidgets-devel
    - kjs-devel
    - kservice-devel
    - kwidgetsaddons-devel
    - kxmlgui-devel
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
